HW8 is completed
AndreyChufelin/homework pull request #8
Opened 2024-07-29 20:36 UTC by AndreyChufelin

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-07-30 06:06 UTC, dshemin requested changes

2024-07-30 06:06 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	c.Stdout = os.Stdout
Критично:

Не проброшен Stdin

2024-07-30 06:06 UTC, dshemin commented on hw08_envdir_tool/main.go
> +	env, _ := ReadDir(os.Args[1])
Важно:

Игнорируется ошибка

2024-08-01 05:29 UTC, agneum approved these changes
Спасибо за выполненное задание. Хорошая работа
Итого: 9 баллов из 10. Принято

Прошу прислать инвайт в репозиторий, чтобы аппрув имел вес

2024-08-01 05:29 UTC, agneum commented on hw08_envdir_tool/env_reader.go
> +		defer file.Close()
Если использовать defer в цикле, то файлы (все) закроются только в конце функции.
Предложил бы вынести код работы с файлом в отдельную функцию

2024-08-02 14:04 UTC, merged